[[redirects]]
from = "/*"
to = "/index.html"
status = 200

# Add security headers
[[headers]]
for = "/*"
[headers.values]
X-Frame-Options = "DENY"
X-XSS-Protection = "1; mode=block"
X-Content-Type-Options = "nosniff"
Referrer-Policy = "strict-origin-when-cross-origin"
Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' *.push-the-button.app *.netlify.app; style-src 'self' 'unsafe-inline' *.push-the-button.app *.netlify.app; img-src 'self' data: blob: *.push-the-button.app *.netlify.app; connect-src 'self' *.push-the-button.app *.netlify.app api.bittails.io api.whatsonchain.com; font-src 'self' *.push-the-button.app *.netlify.app; frame-ancestors 'none';"
Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
Permissions-Policy = "geolocation=(), microphone=(), camera=(), payment=()"